--------------------------------------------------------
--  DDL for Table CANAL
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."CANAL" 
   (	"COD_CANAL" NUMBER(2,0), 
	"DES_CANAL" VARCHAR2(40 CHAR), 
	"ABR_CANAL" VARCHAR2(10 CHAR), 
	"VLR_MINIMO" NUMBER(5,2), 
	"VLR_MAXIMO" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Table CLASSIFICACAO_JUSTIF
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."CLASSIFICACAO_JUSTIF" 
   (	"COD_CLASSIF_JUSTIF" NUMBER(2,0), 
	"DES_CLASSIF_JUSTIF" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."CLASSIFICACAO_JUSTIF"."COD_CLASSIF_JUSTIF" IS 'Código da classificação da justificativa do parâmetro do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."CLASSIFICACAO_JUSTIF"."DES_CLASSIF_JUSTIF" IS 'Descrição da classificação da justificativa do parâmetro do produto';
--------------------------------------------------------
--  DDL for Table HORARIO
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."HORARIO" 
   (	"HOR_REFERENCIA" DATE, 
	"HOR_MIN_REFERENCIA" DATE, 
	"HOR_MAX_REFERENCIA" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."HORARIO"."HOR_REFERENCIA" IS 'Data/Hora da referência do lançamento';
   COMMENT ON COLUMN "APPS_GUANDU"."HORARIO"."HOR_MIN_REFERENCIA" IS 'Data/Hora do horário de referência mínima para início do lançamento';
   COMMENT ON COLUMN "APPS_GUANDU"."HORARIO"."HOR_MAX_REFERENCIA" IS 'Data/Hora do horário de referência máxima para final do lançamento';
--------------------------------------------------------
--  DDL for Table JUSTIF_HORARIO
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."JUSTIF_HORARIO" 
   (	"HOR_REFERENCIA" DATE, 
	"DAT_ATRASO" TIMESTAMP (6), 
	"DES_ATRASO" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_HORARIO"."HOR_REFERENCIA" IS 'Data/Hora referência do lançamento';
   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_HORARIO"."DAT_ATRASO" IS 'Data/Hora que foi justificado o atraso (deve ser automático)';
   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_HORARIO"."DES_ATRASO" IS 'Descrição breve para justificativa do atraso no lançamento';
--------------------------------------------------------
--  DDL for Table JUSTIF_PARAM_PROD
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" 
   (	"COD_PARAM_PRODUTO" NUMBER(3,0), 
	"HOR_REFERENCIA" DATE, 
	"COD_CLASSIF_JUSTIF" NUMBER(2,0), 
	"COD_CANAL" NUMBER(2,0), 
	"DAT_JUST_PARAM_PROD" TIMESTAMP (6), 
	"DES_JUSTIF_PARAM_PROD" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_PARAM_PROD"."COD_PARAM_PRODUTO" IS 'Código de parâmetros do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_PARAM_PROD"."HOR_REFERENCIA" IS 'Data/Hora da referência do lançamento';
   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_PARAM_PROD"."COD_CLASSIF_JUSTIF" IS 'Código da classificação da justificativa do parâmetro do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_PARAM_PROD"."COD_CANAL" IS 'Código do canal na justificativa do parâmetro do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_PARAM_PROD"."DAT_JUST_PARAM_PROD" IS 'Data/Hora da classificação da justificativa do parâmetro do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."JUSTIF_PARAM_PROD"."DES_JUSTIF_PARAM_PROD" IS 'Descrição breve para justificativa do parâmetro do produto';
--------------------------------------------------------
--  DDL for Table LEITURA_LABORATORIO
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" 
   (	"HOR_REFERENCIA" DATE, 
	"COD_CANAL" NUMBER(2,0), 
	"COD_PARAM_PRODUTO" NUMBER(3,0), 
	"COD_FUNCIONARIO" NUMBER(2,0), 
	"VLR_LEITURA" NUMBER(5,2), 
	"DAT_LEITURA" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Table LEITURA_QUALIDADE
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" 
   (	"HOR_REFERENCIA" DATE, 
	"COD_PARAM_PRODUTO" NUMBER(3,0), 
	"VLR_LEITURA" NUMBER(5,2), 
	"DAT_LEITURA" TIMESTAMP (6) DEFAULT SYSDATE, 
	"COD_FUNCIONARIO" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."LEITURA_QUALIDADE"."HOR_REFERENCIA" IS 'Data/Hora da referência do lançamento';
   COMMENT ON COLUMN "APPS_GUANDU"."LEITURA_QUALIDADE"."COD_PARAM_PRODUTO" IS 'Código de parâmetros do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."LEITURA_QUALIDADE"."VLR_LEITURA" IS 'Valor da lançamento do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."LEITURA_QUALIDADE"."DAT_LEITURA" IS 'Data da lançamento do produto (este valor deve ser automático)';
   COMMENT ON COLUMN "APPS_GUANDU"."LEITURA_QUALIDADE"."COD_FUNCIONARIO" IS 'Código do funcionário usuário do sistema';
--------------------------------------------------------
--  DDL for Table LEITURA_VAZAO
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."LEITURA_VAZAO" 
   (	"HOR_REFERENCIA" DATE, 
	"COD_CANAL" NUMBER(2,0), 
	"COD_FUNCIONARIO" NUMBER(3,0), 
	"VLR_LEITURA" NUMBER(5,2), 
	"DAT_LEITURA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Table PARAM_PRODUTO
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."PARAM_PRODUTO" 
   (	"COD_PARAM_PRODUTO" NUMBER(3,0), 
	"DES_PARAM_PRODUTO" VARCHAR2(60 CHAR), 
	"ABR_PARAM_PRODUTO" VARCHAR2(10 CHAR), 
	"VLR_MINIMO" NUMBER(5,2), 
	"VLR_MAXIMO" NUMBER(5,2), 
	"DAT_VIGENCIA" TIMESTAMP (6), 
	"COD_TIP_PARAM_LEITURA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."PARAM_PRODUTO"."COD_PARAM_PRODUTO" IS 'Código de parâmetros do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."PARAM_PRODUTO"."DES_PARAM_PRODUTO" IS 'Desrição de parâmetros do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."PARAM_PRODUTO"."ABR_PARAM_PRODUTO" IS 'Abreviatura de parâmetros do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."PARAM_PRODUTO"."VLR_MINIMO" IS 'Valor mínimo de parâmetro do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."PARAM_PRODUTO"."VLR_MAXIMO" IS 'Valor máximo de parâmetro do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."PARAM_PRODUTO"."DAT_VIGENCIA" IS 'Data de vigência de parâmetro do produto';
   COMMENT ON COLUMN "APPS_GUANDU"."PARAM_PRODUTO"."COD_TIP_PARAM_LEITURA" IS 'Código do tipo de parâmentro de leitura';
--------------------------------------------------------
--  DDL for Table PLANTAO
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."PLANTAO" 
   (	"COD_PLANTAO" NUMBER(1,0), 
	"DES_PLANTAO" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."PLANTAO"."COD_PLANTAO" IS 'Código do plantão';
   COMMENT ON COLUMN "APPS_GUANDU"."PLANTAO"."DES_PLANTAO" IS 'Descrição do plantão';
--------------------------------------------------------
--  DDL for Table TIPO_PARAM_LEITURA
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."TIPO_PARAM_LEITURA" 
   (	"COD_TIP_PARAM_LEITURA" NUMBER(2,0), 
	"DES_TIP_PARAM_LEITURA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."TIPO_PARAM_LEITURA"."COD_TIP_PARAM_LEITURA" IS 'Código do tipo de parâmentro de leitura';
   COMMENT ON COLUMN "APPS_GUANDU"."TIPO_PARAM_LEITURA"."DES_TIP_PARAM_LEITURA" IS 'Descrição do tipo de parâmentro de leitura';
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."USUARIO" 
   (	"COD_FUNCIONARIO" NUMBER(3,0), 
	"COD_MATRICULA" VARCHAR2(8 CHAR), 
	"NOM_FUNCIONARIO" VARCHAR2(40 BYTE), 
	"COD_PERFIL" NUMBER(1,0) DEFAULT 1, 
	"COD_PLANTAO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."USUARIO"."COD_FUNCIONARIO" IS 'Código do funcionário usuário do sistema';
   COMMENT ON COLUMN "APPS_GUANDU"."USUARIO"."COD_MATRICULA" IS 'Código da matrícula';
   COMMENT ON COLUMN "APPS_GUANDU"."USUARIO"."NOM_FUNCIONARIO" IS 'Nome do funcionário usuário do sistema';
   COMMENT ON COLUMN "APPS_GUANDU"."USUARIO"."COD_PERFIL" IS 'Código de perfil do usuário';
   COMMENT ON COLUMN "APPS_GUANDU"."USUARIO"."COD_PLANTAO" IS 'Código do plantão';
--------------------------------------------------------
--  DDL for Table USUARIO_PLANTAO
--------------------------------------------------------

  CREATE TABLE "APPS_GUANDU"."USUARIO_PLANTAO" 
   (	"COD_FUNCIONARIO" NUMBER(3,0), 
	"COD_PLANTAO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;

   COMMENT ON COLUMN "APPS_GUANDU"."USUARIO_PLANTAO"."COD_FUNCIONARIO" IS 'Código do funcionário usuário do sistema';
   COMMENT ON COLUMN "APPS_GUANDU"."USUARIO_PLANTAO"."COD_PLANTAO" IS 'Código do plantão';
--------------------------------------------------------
--  DDL for Index CANAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."CANAL_PK" ON "APPS_GUANDU"."CANAL" ("COD_CANAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index UQ_CANAL_DES
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."UQ_CANAL_DES" ON "APPS_GUANDU"."CANAL" ("DES_CANAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index UQ_CANAL_ABR
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."UQ_CANAL_ABR" ON "APPS_GUANDU"."CANAL" ("ABR_CANAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index CLASSIFICACAO_JUSTIF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."CLASSIFICACAO_JUSTIF_PK" ON "APPS_GUANDU"."CLASSIFICACAO_JUSTIF" ("COD_CLASSIF_JUSTIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index UQ_CLASSIFI_JUSTIF
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."UQ_CLASSIFI_JUSTIF" ON "APPS_GUANDU"."CLASSIFICACAO_JUSTIF" ("DES_CLASSIF_JUSTIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index IDX_HOR_LEITURA
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."IDX_HOR_LEITURA" ON "APPS_GUANDU"."HORARIO" ("HOR_MAX_REFERENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index HORARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."HORARIO_PK" ON "APPS_GUANDU"."HORARIO" ("HOR_REFERENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index JUSTIF_HORARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."JUSTIF_HORARIO_PK" ON "APPS_GUANDU"."JUSTIF_HORARIO" ("HOR_REFERENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index JUSTIF_PARAM_PROD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."JUSTIF_PARAM_PROD_PK" ON "APPS_GUANDU"."JUSTIF_PARAM_PROD" ("HOR_REFERENCIA", "COD_PARAM_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index LEITURA_LAB_CANAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."LEITURA_LAB_CANAL_PK" ON "APPS_GUANDU"."LEITURA_LABORATORIO" ("COD_CANAL", "COD_PARAM_PRODUTO", "HOR_REFERENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index LEITURA_QUALIDADE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."LEITURA_QUALIDADE_PK" ON "APPS_GUANDU"."LEITURA_QUALIDADE" ("HOR_REFERENCIA", "COD_PARAM_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index LEITURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."LEITURA_PK" ON "APPS_GUANDU"."LEITURA_VAZAO" ("COD_CANAL", "HOR_REFERENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index PARAM_PRODUTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."PARAM_PRODUTO_PK" ON "APPS_GUANDU"."PARAM_PRODUTO" ("COD_PARAM_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index PLANTAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."PLANTAO_PK" ON "APPS_GUANDU"."PLANTAO" ("COD_PLANTAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index TIPO_PARAM_LEITURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."TIPO_PARAM_LEITURA_PK" ON "APPS_GUANDU"."TIPO_PARAM_LEITURA" ("COD_TIP_PARAM_LEITURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index UQ_DES_TIP_PARAM_LEITURA
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."UQ_DES_TIP_PARAM_LEITURA" ON "APPS_GUANDU"."TIPO_PARAM_LEITURA" ("DES_TIP_PARAM_LEITURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."USUARIO_PK" ON "APPS_GUANDU"."USUARIO" ("COD_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_NOM_FUNCIONARIO_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."USUARIO_NOM_FUNCIONARIO_UN" ON "APPS_GUANDU"."USUARIO" ("NOM_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_COD_MATRICULA_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."USUARIO_COD_MATRICULA_UN" ON "APPS_GUANDU"."USUARIO" ("COD_MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PLANTAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS_GUANDU"."USUARIO_PLANTAO_PK" ON "APPS_GUANDU"."USUARIO_PLANTAO" ("COD_FUNCIONARIO", "COD_PLANTAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS" ;
--------------------------------------------------------
--  DDL for Trigger USU_COD_FUNCIONARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "APPS_GUANDU"."USU_COD_FUNCIONARIO_TRG" BEFORE
    INSERT ON usuario
    FOR EACH ROW
     WHEN ( new.cod_funcionario IS NULL ) BEGIN
    :new.cod_funcionario := usu_cod_funcionario_seq.nextval;
END;
/
ALTER TRIGGER "APPS_GUANDU"."USU_COD_FUNCIONARIO_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CANAL
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."CANAL" ADD CONSTRAINT "UQ_CANAL_ABR" UNIQUE ("ABR_CANAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."CANAL" ADD CONSTRAINT "UQ_CANAL_DES" UNIQUE ("DES_CANAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."CANAL" ADD CONSTRAINT "CANAL_PK" PRIMARY KEY ("COD_CANAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."CANAL" MODIFY ("DES_CANAL" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."CANAL" MODIFY ("COD_CANAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASSIFICACAO_JUSTIF
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."CLASSIFICACAO_JUSTIF" ADD CONSTRAINT "UQ_CLASSIFI_JUSTIF" UNIQUE ("DES_CLASSIF_JUSTIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."CLASSIFICACAO_JUSTIF" ADD CONSTRAINT "CLASSIFICACAO_JUSTIF_PK" PRIMARY KEY ("COD_CLASSIF_JUSTIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."CLASSIFICACAO_JUSTIF" MODIFY ("DES_CLASSIF_JUSTIF" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."CLASSIFICACAO_JUSTIF" MODIFY ("COD_CLASSIF_JUSTIF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HORARIO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."HORARIO" ADD CONSTRAINT "HORARIO_PK" PRIMARY KEY ("HOR_REFERENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."HORARIO" MODIFY ("HOR_MAX_REFERENCIA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."HORARIO" MODIFY ("HOR_MIN_REFERENCIA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."HORARIO" MODIFY ("HOR_REFERENCIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JUSTIF_HORARIO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."JUSTIF_HORARIO" ADD CONSTRAINT "JUSTIF_HORARIO_PK" PRIMARY KEY ("HOR_REFERENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."JUSTIF_HORARIO" MODIFY ("DES_ATRASO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."JUSTIF_HORARIO" MODIFY ("DAT_ATRASO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."JUSTIF_HORARIO" MODIFY ("HOR_REFERENCIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JUSTIF_PARAM_PROD
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" ADD CONSTRAINT "JUSTIF_PARAM_PROD_PK" PRIMARY KEY ("HOR_REFERENCIA", "COD_PARAM_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" MODIFY ("DES_JUSTIF_PARAM_PROD" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" MODIFY ("DAT_JUST_PARAM_PROD" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" MODIFY ("COD_CLASSIF_JUSTIF" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" MODIFY ("HOR_REFERENCIA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" MODIFY ("COD_PARAM_PRODUTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LEITURA_LABORATORIO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" ADD CONSTRAINT "LEITURA_LAB_CANAL_PK" PRIMARY KEY ("COD_CANAL", "COD_PARAM_PRODUTO", "HOR_REFERENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" MODIFY ("DAT_LEITURA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" MODIFY ("VLR_LEITURA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" MODIFY ("COD_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" MODIFY ("COD_PARAM_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" MODIFY ("COD_CANAL" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" MODIFY ("HOR_REFERENCIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LEITURA_QUALIDADE
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" ADD CONSTRAINT "LEITURA_QUALIDADE_PK" PRIMARY KEY ("HOR_REFERENCIA", "COD_PARAM_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" MODIFY ("COD_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" MODIFY ("VLR_LEITURA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" MODIFY ("COD_PARAM_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" MODIFY ("HOR_REFERENCIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LEITURA_VAZAO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."LEITURA_VAZAO" ADD CONSTRAINT "LEITURA_PK" PRIMARY KEY ("COD_CANAL", "HOR_REFERENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_VAZAO" MODIFY ("DAT_LEITURA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_VAZAO" MODIFY ("VLR_LEITURA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_VAZAO" MODIFY ("COD_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_VAZAO" MODIFY ("COD_CANAL" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."LEITURA_VAZAO" MODIFY ("HOR_REFERENCIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARAM_PRODUTO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."PARAM_PRODUTO" ADD CONSTRAINT "PARAM_PRODUTO_PK" PRIMARY KEY ("COD_PARAM_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."PARAM_PRODUTO" MODIFY ("COD_TIP_PARAM_LEITURA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."PARAM_PRODUTO" MODIFY ("DAT_VIGENCIA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."PARAM_PRODUTO" MODIFY ("VLR_MAXIMO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."PARAM_PRODUTO" MODIFY ("VLR_MINIMO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."PARAM_PRODUTO" MODIFY ("DES_PARAM_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."PARAM_PRODUTO" MODIFY ("COD_PARAM_PRODUTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANTAO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."PLANTAO" ADD CONSTRAINT "PLANTAO_PK" PRIMARY KEY ("COD_PLANTAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."PLANTAO" MODIFY ("DES_PLANTAO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."PLANTAO" MODIFY ("COD_PLANTAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_PARAM_LEITURA
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."TIPO_PARAM_LEITURA" ADD CONSTRAINT "UQ_DES_TIP_PARAM_LEITURA" UNIQUE ("DES_TIP_PARAM_LEITURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."TIPO_PARAM_LEITURA" ADD CONSTRAINT "TIPO_PARAM_LEITURA_PK" PRIMARY KEY ("COD_TIP_PARAM_LEITURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."TIPO_PARAM_LEITURA" MODIFY ("DES_TIP_PARAM_LEITURA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."TIPO_PARAM_LEITURA" MODIFY ("COD_TIP_PARAM_LEITURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."USUARIO" ADD CONSTRAINT "USUARIO_COD_MATRICULA_UN" UNIQUE ("COD_MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."USUARIO" ADD CONSTRAINT "USUARIO_NOM_FUNCIONARIO_UN" UNIQUE ("NOM_FUNCIONARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("COD_FUNCIONARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."USUARIO" ADD CONSTRAINT "CK_PERFIL" CHECK ( cod_perfil BETWEEN 1 AND 3
                                     OR cod_perfil IN ( 1, 2, 3 ) ) ENABLE;
  ALTER TABLE "APPS_GUANDU"."USUARIO" MODIFY ("COD_PLANTAO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."USUARIO" MODIFY ("COD_PERFIL" CONSTRAINT "1" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."USUARIO" MODIFY ("NOM_FUNCIONARIO" CONSTRAINT "NNC_USU_NOM_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."USUARIO" MODIFY ("COD_MATRICULA" CONSTRAINT "NNC_USU_COD_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."USUARIO" MODIFY ("COD_FUNCIONARIO" CONSTRAINT "NNC_USU_USU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO_PLANTAO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."USUARIO_PLANTAO" ADD CONSTRAINT "USUARIO_PLANTAO_PK" PRIMARY KEY ("COD_FUNCIONARIO", "COD_PLANTAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SISTEMAS"  ENABLE;
  ALTER TABLE "APPS_GUANDU"."USUARIO_PLANTAO" MODIFY ("COD_PLANTAO" NOT NULL ENABLE);
  ALTER TABLE "APPS_GUANDU"."USUARIO_PLANTAO" MODIFY ("COD_FUNCIONARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table JUSTIF_HORARIO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."JUSTIF_HORARIO" ADD CONSTRAINT "JUSTIF_HORARIO_HORARIO_FK" FOREIGN KEY ("HOR_REFERENCIA")
	  REFERENCES "APPS_GUANDU"."HORARIO" ("HOR_REFERENCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUSTIF_PARAM_PROD
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" ADD CONSTRAINT "JUSTIF_PARAM_PROD_CLASSIF_FK" FOREIGN KEY ("COD_CLASSIF_JUSTIF")
	  REFERENCES "APPS_GUANDU"."CLASSIFICACAO_JUSTIF" ("COD_CLASSIF_JUSTIF") ENABLE;
  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" ADD CONSTRAINT "JUSTIF_PAR_PROD_ADUTORA_FK" FOREIGN KEY ("COD_CANAL")
	  REFERENCES "APPS_GUANDU"."CANAL" ("COD_CANAL") ENABLE;
  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" ADD CONSTRAINT "JUSTIF_PAR_PROD_HORARIO_FK" FOREIGN KEY ("HOR_REFERENCIA")
	  REFERENCES "APPS_GUANDU"."HORARIO" ("HOR_REFERENCIA") ENABLE;
  ALTER TABLE "APPS_GUANDU"."JUSTIF_PARAM_PROD" ADD CONSTRAINT "JUSTIF_PAR_PROD_PAR_PRODUTO_FK" FOREIGN KEY ("COD_PARAM_PRODUTO")
	  REFERENCES "APPS_GUANDU"."PARAM_PRODUTO" ("COD_PARAM_PRODUTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEITURA_LABORATORIO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" ADD CONSTRAINT "LEITURA_LAB_CANAL_FK" FOREIGN KEY ("COD_CANAL")
	  REFERENCES "APPS_GUANDU"."CANAL" ("COD_CANAL") ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" ADD CONSTRAINT "LEITURA_LAB_HORARIO_FK" FOREIGN KEY ("HOR_REFERENCIA")
	  REFERENCES "APPS_GUANDU"."HORARIO" ("HOR_REFERENCIA") ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" ADD CONSTRAINT "LEITURA_LAB_PARAM_PROD_FK" FOREIGN KEY ("COD_PARAM_PRODUTO")
	  REFERENCES "APPS_GUANDU"."PARAM_PRODUTO" ("COD_PARAM_PRODUTO") ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_LABORATORIO" ADD CONSTRAINT "LEITURA_LAB_USUARIO_FK" FOREIGN KEY ("COD_FUNCIONARIO")
	  REFERENCES "APPS_GUANDU"."USUARIO" ("COD_FUNCIONARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEITURA_QUALIDADE
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" ADD CONSTRAINT "LEITURAQ_PARAM_PRODUTO_FK" FOREIGN KEY ("COD_PARAM_PRODUTO")
	  REFERENCES "APPS_GUANDU"."PARAM_PRODUTO" ("COD_PARAM_PRODUTO") ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" ADD CONSTRAINT "LEITURAQ_RESPONSAVEL_FK" FOREIGN KEY ("COD_FUNCIONARIO")
	  REFERENCES "APPS_GUANDU"."USUARIO" ("COD_FUNCIONARIO") ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_QUALIDADE" ADD CONSTRAINT "LEITURA_QUALIDADE_HORARIO_FK" FOREIGN KEY ("HOR_REFERENCIA")
	  REFERENCES "APPS_GUANDU"."HORARIO" ("HOR_REFERENCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEITURA_VAZAO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."LEITURA_VAZAO" ADD CONSTRAINT "LEITURA_VAZOES_USUARIO_FK" FOREIGN KEY ("COD_FUNCIONARIO")
	  REFERENCES "APPS_GUANDU"."USUARIO" ("COD_FUNCIONARIO") ENABLE;
  ALTER TABLE "APPS_GUANDU"."LEITURA_VAZAO" ADD CONSTRAINT "LEITURA_VAZ_HORARIO_FK" FOREIGN KEY ("HOR_REFERENCIA")
	  REFERENCES "APPS_GUANDU"."HORARIO" ("HOR_REFERENCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARAM_PRODUTO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."PARAM_PRODUTO" ADD CONSTRAINT "PARAM_PRODUTO_TIPO_PARAM_FK" FOREIGN KEY ("COD_TIP_PARAM_LEITURA")
	  REFERENCES "APPS_GUANDU"."TIPO_PARAM_LEITURA" ("COD_TIP_PARAM_LEITURA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO_PLANTAO
--------------------------------------------------------

  ALTER TABLE "APPS_GUANDU"."USUARIO_PLANTAO" ADD CONSTRAINT "USUARIO_PLANTAO_PLANTAO_FK" FOREIGN KEY ("COD_PLANTAO")
	  REFERENCES "APPS_GUANDU"."PLANTAO" ("COD_PLANTAO") ENABLE;
  ALTER TABLE "APPS_GUANDU"."USUARIO_PLANTAO" ADD CONSTRAINT "USUARIO_PLANTAO_USUARIO_FK" FOREIGN KEY ("COD_FUNCIONARIO")
	  REFERENCES "APPS_GUANDU"."USUARIO" ("COD_FUNCIONARIO") ENABLE;
